apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200  
    access: proxy
    isDefault: true
    editable: true 

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    editable: true