server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

compactor:
  compaction:
    compacted_block_retention: 24h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

overrides:
  per_tenant_override_config: null