receivers:
  solace:
    broker: ${env:BROKER_AMQP_HOST}:${env:BROKER_AMQP_PORT}
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: ${env:BROKER_OTEL_USERNAME}
        password: ${env:BROKER_OTEL_PASSWORD}
    queue: queue://#telemetry-${env:BROKER_OTEL_QUEUE_NAME}
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity:
  otlp:
    endpoint: ${env:TEMPO_HOST}:${env:TEMPO_PORT}
    tls:
      insecure: true
      insecure_skip_verify: true
    sending_queue:
      enabled: true
      queue_size: 100000
    retry_on_failure:
      enabled: true
      initial_interval: 2s
      max_interval: 15s
      max_elapsed_time: 120s
  prometheus:
    endpoint: 0.0.0.0:9464

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  pipelines:
    traces:
      receivers: [otlp, solace]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

