receivers:
  solace:
    broker: ${env:BROKER_AMQP_HOST}:${env:BROKER_AMQP_PORT}
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: ${env:BROKER_OTEL_USERNAME}
        password: ${env:BROKER_OTEL_PASSWORD}
    queue: queue://#telemetry-otel
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


processors:
  batch:
    timeout: 5s

exporters:
  debug:
    verbosity:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
      insecure_skip_verify: true
    sending_queue:
      enabled: true
      queue_size: 5000  # Adjust queue size for better control of memory usage
    retry_on_failure:
      enabled: true
      max_interval: 30s
      max_elapsed_time: 300s
  prometheus:
    endpoint: 0.0.0.0:9464

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  pipelines:
    traces:
      receivers: [otlp, solace]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

